<?php
//  ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** *****  //
//  This file creates any custom post types we need for our theme. Get started
//  by un-commenting everything below, and customizing the cpt to suit.
//  ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** *****  //
function create_prop_post_types()
{
  $labels = array(
    'name'                  => _x( 'Projects', 'Post Type General Name', 'text_domain' ),
    'singular_name'         => _x( 'Project', 'Post Type Singular Name', 'text_domain' ),
    'menu_name'             => __( 'Projects', 'text_domain' ),
    'name_admin_bar'        => __( 'Projects', 'text_domain' ),
    'archives'              => __( 'Item Archives', 'text_domain' ),
    'parent_item_colon'     => __( 'Parent Project:', 'text_domain' ),
    'all_items'             => __( 'All Project', 'text_domain' ),
    'add_new_item'          => __( 'Add New Project', 'text_domain' ),
    'add_new'               => __( 'Add New Project', 'text_domain' ),
    'new_item'              => __( 'New Project', 'text_domain' ),
    'edit_item'             => __( 'Edit Project', 'text_domain' ),
    'update_item'           => __( 'Update Project', 'text_domain' ),
    'view_item'             => __( 'View Project', 'text_domain' ),
    'search_items'          => __( 'Search Project', 'text_domain' ),
    'not_found'             => __( 'Not found', 'text_domain' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
    'featured_image'        => __( 'Project Featured Image', 'text_domain' ),
    'set_featured_image'    => __( 'Set Project Featured image', 'text_domain' ),
    'remove_featured_image' => __( 'Remove Project Featured image', 'text_domain' ),
    'use_featured_image'    => __( 'Use as Project Featured image', 'text_domain' ),
    'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
    'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
    'items_list'            => __( 'Project list', 'text_domain' ),
    'items_list_navigation' => __( 'Project list navigation', 'text_domain' ),
    'filter_items_list'     => __( 'Filter Project list', 'text_domain' ),
  );
  $args = array(
    'label'                 => __( 'Project', 'text_domain' ),
    'description'           => __( 'Project', 'text_domain' ),
    'labels'                => $labels,
    'supports'              => array('thumbnail', 'title', 'revisions', 'excerpt'),
    'taxonomies'            => array( ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 25,
    'menu_icon'             => 'dashicons-hammer',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'post',
    'rewrite'               => array('slug' => 'partnerships/current-partnerships', 'with_front' => false)
  );

  register_post_type( 'project', $args );

  $labels = array(
    'name'                  => _x( 'Latest updates', 'Post Type General Name', 'text_domain' ),
    'singular_name'         => _x( 'Latest update', 'Post Type Singular Name', 'text_domain' ),
    'menu_name'             => __( 'Latest updates', 'text_domain' ),
    'name_admin_bar'        => __( 'Latest updates', 'text_domain' ),
    'archives'              => __( 'Item Archives', 'text_domain' ),
    'parent_item_colon'     => __( 'Parent Update:', 'text_domain' ),
    'all_items'             => __( 'All Latest Updates', 'text_domain' ),
    'add_new_item'          => __( 'Add New Latest Update', 'text_domain' ),
    'add_new'               => __( 'Add New Latest Update', 'text_domain' ),
    'new_item'              => __( 'New Latest Update', 'text_domain' ),
    'edit_item'             => __( 'Edit Latest Update', 'text_domain' ),
    'update_item'           => __( 'Update Latest Update', 'text_domain' ),
    'view_item'             => __( 'View Latest Update', 'text_domain' ),
    'search_items'          => __( 'Search Latest Update', 'text_domain' ),
    'not_found'             => __( 'Not found', 'text_domain' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
    'featured_image'        => __( 'Latest Update Featured Image', 'text_domain' ),
    'set_featured_image'    => __( 'Set Latest Update Featured image', 'text_domain' ),
    'remove_featured_image' => __( 'Remove Latest Update Featured image', 'text_domain' ),
    'use_featured_image'    => __( 'Use as Latest Update Featured image', 'text_domain' ),
    'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
    'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
    'items_list'            => __( 'Latest Update list', 'text_domain' ),
    'items_list_navigation' => __( 'Latest Update list navigation', 'text_domain' ),
    'filter_items_list'     => __( 'Filter Latest Update list', 'text_domain' ),
  );
  $args = array(
    'label'                 => __( 'Latest update', 'text_domain' ),
    'description'           => __( 'Latest update', 'text_domain' ),
    'labels'                => $labels,
    'supports'              => array('thumbnail', 'title', 'revisions', 'excerpt'),
    'taxonomies'            => array( ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 25,
    'menu_icon'             => 'dashicons-info-outline',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'post',
    'rewrite'               => array('slug' => 'partnerships/latest-updates', 'with_front' => false)
  );

  register_post_type( 'latest-update', $args );

  $labels = array(
    'name'                  => _x( 'People', 'Post Type General Name', 'text_domain' ),
    'singular_name'         => _x( 'Person', 'Post Type Singular Name', 'text_domain' ),
    'menu_name'             => __( 'People', 'text_domain' ),
    'name_admin_bar'        => __( 'People', 'text_domain' ),
    'archives'              => __( 'Item Archives', 'text_domain' ),
    'parent_item_colon'     => __( 'Parent Person:', 'text_domain' ),
    'all_items'             => __( 'All People', 'text_domain' ),
    'add_new_item'          => __( 'Add New Person', 'text_domain' ),
    'add_new'               => __( 'Add New Person', 'text_domain' ),
    'new_item'              => __( 'New Person', 'text_domain' ),
    'edit_item'             => __( 'Edit Person', 'text_domain' ),
    'update_item'           => __( 'Update Person', 'text_domain' ),
    'view_item'             => __( 'View Person', 'text_domain' ),
    'search_items'          => __( 'Search People', 'text_domain' ),
    'not_found'             => __( 'Not found', 'text_domain' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
    'featured_image'        => __( 'Person Featured Image', 'text_domain' ),
    'set_featured_image'    => __( 'Set Person Featured image', 'text_domain' ),
    'remove_featured_image' => __( 'Remove Person Featured image', 'text_domain' ),
    'use_featured_image'    => __( 'Use as Person Featured image', 'text_domain' ),
    'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
    'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
    'items_list'            => __( 'People list', 'text_domain' ),
    'items_list_navigation' => __( 'People list navigation', 'text_domain' ),
    'filter_items_list'     => __( 'Filter People list', 'text_domain' ),
  );
  $args = array(
    'label'                 => __( 'People', 'text_domain' ),
    'description'           => __( 'People', 'text_domain' ),
    'labels'                => $labels,
    'supports'              => array('thumbnail', 'editor', 'title', 'revisions'),
    'taxonomies'            => array( ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 25,
    'menu_icon'             => 'dashicons-universal-access',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'post',
    'rewrite'               => array('slug' => 'who-we-are/our-team', 'with_front' => false)
  );

  register_post_type( 'people', $args );


  $labels = array(
    'name'                  => _x( 'Questions', 'Post Type General Name', 'text_domain' ),
    'singular_name'         => _x( 'Question', 'Post Type Singular Name', 'text_domain' ),
    'menu_name'             => __( 'Questions', 'text_domain' ),
    'name_admin_bar'        => __( 'Questions', 'text_domain' ),
    'archives'              => __( 'Item Archives', 'text_domain' ),
    'parent_item_colon'     => __( 'Parent Question:', 'text_domain' ),
    'all_items'             => __( 'All Questions', 'text_domain' ),
    'add_new_item'          => __( 'Add New Question', 'text_domain' ),
    'add_new'               => __( 'Add New Question', 'text_domain' ),
    'new_item'              => __( 'New Question', 'text_domain' ),
    'edit_item'             => __( 'Edit Question', 'text_domain' ),
    'update_item'           => __( 'Update Question', 'text_domain' ),
    'view_item'             => __( 'View Question', 'text_domain' ),
    'search_items'          => __( 'Search Questions', 'text_domain' ),
    'not_found'             => __( 'Not found', 'text_domain' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
    'featured_image'        => __( 'Question Featured Image', 'text_domain' ),
    'set_featured_image'    => __( 'Set Question Featured image', 'text_domain' ),
    'remove_featured_image' => __( 'Remove Question Featured image', 'text_domain' ),
    'use_featured_image'    => __( 'Use as Question Featured image', 'text_domain' ),
    'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
    'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
    'items_list'            => __( 'Questions list', 'text_domain' ),
    'items_list_navigation' => __( 'Questions list navigation', 'text_domain' ),
    'filter_items_list'     => __( 'Filter Questions list', 'text_domain' ),
  );
  $args = array(
    'label'                 => __( 'Questions', 'text_domain' ),
    'description'           => __( 'Questions', 'text_domain' ),
    'labels'                => $labels,
    'supports'              => array('title', 'revisions'),
    'taxonomies'            => array( ),
    'hierarchical'          => false,
    'public'                => false,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 25,
    'menu_icon'             => 'dashicons-format-status',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => true,
    'publicly_queryable'    => false,
    'capability_type'       => 'post',
  );

  register_post_type( 'questions', $args );

  $labels = array(
    'name'                  => _x( 'Jobs', 'Post Type General Name', 'text_domain' ),
    'singular_name'         => _x( 'Job', 'Post Type Singular Name', 'text_domain' ),
    'menu_name'             => __( 'Jobs', 'text_domain' ),
    'name_admin_bar'        => __( 'Jobs', 'text_domain' ),
    'archives'              => __( 'Item Archives', 'text_domain' ),
    'parent_item_colon'     => __( 'Parent Job:', 'text_domain' ),
    'all_items'             => __( 'All Jobs', 'text_domain' ),
    'add_new_item'          => __( 'Add New Job', 'text_domain' ),
    'add_new'               => __( 'Add New Job', 'text_domain' ),
    'new_item'              => __( 'New Job', 'text_domain' ),
    'edit_item'             => __( 'Edit Job', 'text_domain' ),
    'update_item'           => __( 'Update Job', 'text_domain' ),
    'view_item'             => __( 'View Job', 'text_domain' ),
    'search_items'          => __( 'Search Jobs', 'text_domain' ),
    'not_found'             => __( 'Not found', 'text_domain' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
    'featured_image'        => __( 'Job Featured Image', 'text_domain' ),
    'set_featured_image'    => __( 'Set Job Featured image', 'text_domain' ),
    'remove_featured_image' => __( 'Remove Job Featured image', 'text_domain' ),
    'use_featured_image'    => __( 'Use as Job Featured image', 'text_domain' ),
    'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
    'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
    'items_list'            => __( 'Jobs list', 'text_domain' ),
    'items_list_navigation' => __( 'Jobs list navigation', 'text_domain' ),
    'filter_items_list'     => __( 'Filter Jobs list', 'text_domain' ),
  );
  $args = array(
    'label'                 => __( 'Jobs', 'text_domain' ),
    'description'           => __( 'Jobs', 'text_domain' ),
    'labels'                => $labels,
    'supports'              => array('editor', 'title', 'revisions'),
    'taxonomies'            => array( ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 25,
    'menu_icon'             => 'dashicons-groups',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'post',
    'rewrite'               => array('slug' => 'who-we-are/vacancies', 'with_front' => false)
  );

  register_post_type( 'job', $args );
    //  Register any additional CPTs here  //
    flush_rewrite_rules();
}
add_action( 'init', 'create_prop_post_types' );
